[colors.bright]
blue = "#83a598"  # Gruvbox: Bright Blue
cyan = "#8ec07c"  # Gruvbox: Bright Aqua
green = "#b8bb26"  # Gruvbox: Bright Green
magenta = "#d3869b"  # Gruvbox: Bright Purple
red = "#fb4934"  # Gruvbox: Bright Red
yellow = "#fabd2f"  # Gruvbox: Bright Yellow

[colors.dim]
blue = "#076678"  # Gruvbox: Dim Blue
cyan = "#427b58"  # Gruvbox: Dim Aqua
green = "#79740e"  # Gruvbox: Dim Green
magenta = "#8f3f71"  # Gruvbox: Dim Purple
red = "#9d0006"  # Gruvbox: Dim Red
yellow = "#b57614"  # Gruvbox: Dim Yellow

[colors.normal]
blue = "#458588"  # Gruvbox: Blue
cyan = "#689d6a"  # Gruvbox: Aqua
green = "#98971a"  # Gruvbox: Green
magenta = "#b16286"  # Gruvbox: Purple
red = "#cc241d"  # Gruvbox: Red
white = "#ebdbb2"  # Gruvbox: Foreground
yellow = "#d79921"  # Gruvbox: Yellow

[colors.primary]
background = "#282828"  # Gruvbox: Background
foreground = "#ebdbb2"  # Gruvbox: Foreground

[env]
TERM = "alacritty"

[font]
size = 16.9
#offset.y = 0  # For line spacing (default: 0)

[font.normal]
#family = "DejaVu Sans Mono"
family = "JetBrains Mono NL"
style = "Regular"

[window]
dynamic_title = true
title = "Alacritty"
#opacity = 0.95
